import { type LearnPage } from './types';
import { parseCards } from '../engine/cards';
import { evaluate, describeScore, CATEGORY_NAMES } from '../engine/evaluator';
import { choose } from '../engine/math';
import { fullDeck } from '../engine/cards';
import { forEachCombination } from '../engine/math';
import { categoryOf } from '../engine/evaluator';
import { n, pc } from './helpers';

function categoryTable() {
  const counts = new Array<number>(9).fill(0);
  forEachCombination(fullDeck(), 5, (hand) => {
    counts[categoryOf(evaluate(hand))]!++;
  });
  const total = choose(52, 5);
  return {
    head: ['Rank', 'Category', 'Five-card hands', 'Share'],
    rows: CATEGORY_NAMES.map((name, i) => [String(9 - i), name, counts[i]!.toLocaleString(), pc(counts[i]! / total, 3)]).reverse(),
  };
}

const ex = (hero: string, board: string): string => describeScore(evaluate([...parseCards(hero), ...parseCards(board)]));

export const m1: LearnPage = {
  id: 'M1',
  title: 'Vocabulary, hand rankings and the shape of a hand',
  summary: 'The words, the ten categories, and how five cards are chosen from seven.',
  drills: ['hand-ranking', 'best-hand'],
  blocks: [
    { kind: 'h', text: 'The words' },
    {
      kind: 'terms',
      items: [
        { term: 'Hole cards', definition: () => 'The two cards dealt face down to you. Nobody else sees them.' },
        { term: 'Board', definition: () => 'The community cards dealt face up in the middle, shared by everyone. Up to five.' },
        { term: 'Street', definition: () => 'A round of betting. There are four: preflop (no board yet), the flop (three board cards), the turn (a fourth) and the river (a fifth).' },
        { term: 'Pot', definition: () => 'All chips bet so far, sitting in the middle. The winner takes it.' },
        { term: 'Bet, call, raise, fold, check', definition: () => 'Bet: put chips in when nobody has yet. Call: match the current bet. Raise: increase it. Fold: give up the hand and any chips already in. Check: pass without betting when no bet is pending.' },
        { term: 'Position', definition: () => 'Where you act in the betting order. Acting last is an advantage because you see what others do first.' },
        { term: 'Showdown', definition: () => 'After the river betting, remaining players reveal their cards and the best five-card hand wins.' },
        { term: 'Hero, villain', definition: () => 'Hero is you. Villain is the opponent. Both are conventions, not judgements.' },
        { term: 'Big blind', definition: () => 'A forced bet that starts the pot. Stack sizes are often measured in big blinds (bb) so they compare across games.' },
      ],
    },
    { kind: 'h', text: 'The ten categories' },
    {
      kind: 'p',
      text: () =>
        `A hand is the best five cards you can select from your two hole cards plus the board, seven cards in all once the river is dealt. Hands fall into categories ranked by rarity. The table is generated by scoring every one of the ${choose(52, 5).toLocaleString()} possible five-card hands.`,
    },
    { kind: 'table', caption: 'All five-card hands, scored by the engine', build: categoryTable },
    {
      kind: 'p',
      text: () =>
        'Within a category, higher ranks win: a pair of kings beats a pair of nines. When the category and its main ranks tie, the remaining cards (kickers) decide. Suits never break ties. If the best five cards are identical, the pot is split.',
    },
    { kind: 'p', text: () => 'A straight is five consecutive ranks. The ace plays high (ten to ace) or low (ace to five), never around the corner. A flush is five cards of one suit. A full house is three of one rank and two of another.' },
    { kind: 'h', text: 'Five from seven' },
    {
      kind: 'p',
      text: () =>
        'You do not have to use both hole cards, or either. The board can play by itself. Reading which five cards form the hand, instantly, is the whole skill of this module, and everything after it depends on it.',
    },
    { kind: 'example', hero: 'Ah Kh', board: '7h 7d 7c 2h 9h', text: () => `Five hearts and three sevens. The best five cards make a ${ex('Ah Kh', '7h 7d 7c 2h 9h')}, which outranks the three of a kind.` },
    { kind: 'example', hero: 'Ah 2d', board: 'Kc Kd 9s 9h Qc', text: () => `The board already holds two pair. Your best hand is ${ex('Ah 2d', 'Kc Kd 9s 9h Qc')}: the ace replaces the queen as the fifth card. Anyone without an ace has exactly the board.` },
    { kind: 'example', hero: 'Jh Th', board: '9h 8h 2c Qs 3d', text: () => `The straight arrived on the turn: ${ex('Jh Th', '9h 8h 2c Qs 3d')}. Note the flush draw did not complete, and it does not matter.` },
    { kind: 'example', hero: 'As Ad', board: 'Ac 5c 6c 7c 8c', text: () => `Three aces, but the board makes a ${ex('As Ad', 'Ac 5c 6c 7c 8c')} for everyone. Your set is irrelevant, and anyone holding the nine of clubs or the four of clubs beats the board.` },
    {
      kind: 'p',
      text: () =>
        'Why this gates everything else: counting outs (module 2) means naming the cards that improve your hand, which requires seeing instantly that a board pairing turns a flush draw into a loser against a full house. Drill the two hand-reading exercises until they are fast and automatic.',
    },
  ],
};
